package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name = "logging",
    srcs = [
        "logging.h",
    ],
    deps = [
        "@com_google_glog//:glog",
        "@spdlog//:spdlog",
    ],
)